import requests

unique_id = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaWQiOiJ6eWJfMzA3Y2RhZjc1OTVjNzM0NGM0MGRiMzYyNGNmMTllMzciLCJ3aWR0aCI6NzM5LCJoZWlnaHQiOjEzNiwiY3VpZCI6IjUwNDE1MjczNTE1Mjc1NjMzNjQ0NWE0YzU3NjIyYjcwMzM2YzY3NzE0ZjVhNWE2ZDMxNzc0YTQxNzk3MzMyNTg3MDU0NGE1MTQ3NDEzZDNkIiwiaXAiOiIxNzIuMjkuMTI5LjE5MyIsImlhdCI6MTYzMTA2OTM0MCwiZXhwIjoxNjMxMDY5MzcwfQ.mFQLQqEGNatiFshrb56YVGJlWnDw-moyxibBwqgAfjo"
url = f"https://plat-miniapp.zuoyebang.com/miniapp/api/search/questions?q={'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaWQiOiJ6eWJfMzY5YzJjMzBhMTc0MGE1MGZkMzNhNjlhNjNiOTgyOTYiLCJ3aWR0aCI6NDA5NiwiaGVpZ2h0IjoxODg4LCJpcCI6IjEwLjk4LjEzMC4yNTQiLCJpYXQiOjE3NDI5OTgxMjYsImV4cCI6MTc0Mjk5ODE1Nn0.tEH5Zx5dcaAkZ17hxFimcNfrzwOAUY2TVKf4hgbDJ_k'}"
response = requests.get(url)
print(response.json())